name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- master
- refs/tags/*
pr:
- master
jobs:
- job: Test_Build_Deploy
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - task: Powershell@2
      displayName: 'Test'
      inputs:
        targetType: 'filePath'
        filePath: .\Build\Start-Build.ps1
        arguments: -Task Test -Verbose
        errorActionPreference: 'stop'
        failOnStderr: true

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'PS_Win2016'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Code Coverage Results'
      condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '**/TestCoverage.xml'

    - task: Powershell@2
      displayName: 'Set build version'
      condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      env:
        BUILD_NAME: $(Build.BuildNumber)
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      inputs:
        targetType: 'filePath'
        filePath: .\Build\Start-Build.ps1
        arguments: -Task SetBuildVersion -Verbose
        errorActionPreference: 'stop'
        failOnStderr: true

    - task: Powershell@2
      displayName: 'Build and deploy'
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        PSREPO_APIKEY: $(psrepo.apikey)
      inputs:
        targetType: 'filePath'
        filePath: .\Build\Start-Build.ps1
        arguments: -Task Deploy -Verbose
        errorActionPreference: 'stop'
        failOnStderr: true
